general:
    data_type: gathered
    run: DLSraw

gathered:
    input: /gpfs/cfel/fsds/labs/agipd/calibration/scratch/user/kuhnm/percival_tests/processed
    output: /gpfs/cfel/fsds/labs/agipd/calibration/scratch/user/kuhnm/percival_tests/processed

    measurement: adccal

    adc: 0
    col: 100
    rows: null

    method: [plot, hist, hist_2d]
    #method: [plot_sample_vs_reset]

processed:
    input: /gpfs/cfel/fsds/labs/agipd/calibration/scratch/user/kuhnm/percival_tests/processed
    output: /gpfs/cfel/fsds/labs/agipd/calibration/scratch/user/kuhnm/percival_tests/processed

    measurement: adccal

    adc: 0
    col: 100
    rows: null

    method: [plot]
