general:
    data_type: gathered
    run: DLSraw

    plot_sample: True
    plot_reset: True
    plot_combined: True

raw:
    input: /gpfs/cfel/fsds/labs/agipd/calibration/scratch/user/kuhnm/percival_tests/raw/PSVoltFromVin_fn_reduced_iFbiasN5000/PSVoltFromVin15000_DLSraw.h5
    output: /gpfs/cfel/fsds/labs/agipd/calibration/scratch/user/kuhnm/percival_tests/processed

    measurement: adccal

    frame: 0
    col: null
    rows: null

    method: [plot]

gathered:
    input: /gpfs/cfel/fsds/labs/agipd/calibration/scratch/user/kuhnm/percival_tests/processed
    output: /gpfs/cfel/fsds/labs/agipd/calibration/scratch/user/kuhnm/percival_tests/processed

    measurement: adccal

    adc: 0
    col: 100
    rows: null

    method: [plot, hist, hist_2d]
    #method: [plot_sample_vs_reset]

processed:
    input: /gpfs/cfel/fsds/labs/agipd/calibration/scratch/user/kuhnm/percival_tests/processed
    output: /gpfs/cfel/fsds/labs/agipd/calibration/scratch/user/kuhnm/percival_tests/processed

    measurement: adccal

    adc: 0
    col: 100
    rows: null

    method: [plot]
