general:
    run_type: process
    n_cols: 1440

    measurement: process_adccal_default

    run: DLSraw

    n_processes: 1

all:
    input: &input /Users/ben/PostDoc/P2M_HDF5/
    output: &output /Users/ben/PostDoc/P2M_HDF5/

gather:
    method: null

    input: *input
    output: *output

process:
    method: process_adccal_default

    input: *output
    output: *output

